config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :kittens
  root 'kittens#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to @kitten, notice: 'Kitten was successfully created.'
    else
      render :new
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      redirect_to @kitten, notice: 'Kitten was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    redirect_to kittens_url, notice: 'Kitten was successfully destroyed.'
  end


  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/edit.html.erb
<%= form_with(model: @kitten, local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :age %><br>
    <%= form.number_field :age %>
  </p>

  <p>
    <%= form.label :cuteness %><br>
    <%= form.number_field :cuteness %>
  </p>

  <p>
    <%= form.label :softness %><br>
    <%= form.number_field :softness %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back to Kittens List', kittens_path %>

app/views/kittens/index.html.erb
<%= link_to 'New Kitten', new_kitten_path %>

<h1>All Kittens</h1>
<ul>
  <% @kittens.each do |kitten| %>
    <li><%= link_to kitten.name, kitten_path(kitten) %></li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<%= form_with(model: @kitten, local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :age %><br>
    <%= form.number_field :age %>
  </p>

  <p>
    <%= form.label :cuteness %><br>
    <%= form.number_field :cuteness %>
  </p>

  <p>
    <%= form.label :softness %><br>
    <%= form.number_field :softness %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>
<%= link_to 'Back to Kittens List', kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>